name: main
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'dev'
  pull_request:
    types: [opened, edited, synchronize, reopened]


jobs:
  build-static-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # tag=v4.1.5
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # tag=v5.0.1
      with:
        go-version: 1.22.0
    - name: Build
      run: make build
    - name: FMT
      run: make fmt
    - name: VET
      run: make vet
    - name: LINT
      run: make lint
      env:
        LINT: true
  FV:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # tag=v4.1.5
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # tag=v5.0.1
      with:
        go-version: 1.22.0
    - name: fv
      run: make create-cluster fv
      env:
        FV: true